### ISSUE TITLE
Create install scripts for both Linux and Windows targets

### ISSUE THREAD

**Issue by erogers88** [erogers88/dotfiles#5]

**Comment by erogers88** [comment]
For Windows this needs to get the user directory on the host to drop the alacritty config in the correct location. It could possibly also install win32yank.

**Comment by erogers88** [comment]
This is the Windows Path to the alacritty config:

```
C:\Users\$username\AppData\Roaming\alacritty\alacritty.yml
```

**Comment by erogers88** [comment]
Windows-specific shell config for alacritty

```
shell:
  program: wsl
  args:
    - "--cd /home/$username"
    - "tmux"
```
